### PR TITLE
here is my model by using Py with LSTM method

### PR DESCRIPTION
**Pull request by PRIYANSHU2026**
I achieved 96 % accuracy by using this model issue no #36

### CODE REVIEW

**Comment by PRIYANSHU2026** [comment]
sir please look into it

**Comment by PRIYANSHU2026** [comment]
hey any body is there

**Comment by PRIYANSHU2026** [comment]
hey any body is there

**Comment by PRIYANSHU2026** [comment]
Sir  please see

**Review by jaibhedia — APPROVED** [review]

**Pull request merged**
