### PR TITLE
Removed the UI overflow on main page and Wallet Connect page

### PR DESCRIPTION
**Pull request by a-m-a-nkumar**
Removed the UI overflow to make the ui more responsive.

Screenshot (218)

Screenshot (220)

Here is the screenshot of page after the edit.

image

Screenshot (223)

### CODE REVIEW

**Comment by a-m-a-nkumar** [comment]
@jaibhedia I have solved the issue #35 . Please review.

**Comment by jaibhedia** [comment]
@a-m-a-nkumar Thank you for the PR, I have seen you have made some other changes as well, can you just document it.

**Comment by a-m-a-nkumar** [comment]
@jaibhedia should i share a document listing all the changes or just mention all my work here in the comment section??

**Comment by jaibhedia** [comment]
Sure.

**Comment by jaibhedia** [comment]
You can mention it here in the comments as well, no issues.

**Comment by a-m-a-nkumar** [comment]
Home Page UI Overflow Fix:

Problem: The Home page had a UI overflow issue on the right side, causing a poor user experience.
Solution: To address this, I used a SingleChildScrollView widget with horizontal scrolling enabled. This allows the content to be properly contained and scrollable horizontally, eliminating the overflow issue. I also made changes to the header section of the home page.

Login Section UI Improvement:

Problem: The Login section had an issue where the UI overflow caused the Metamask login button to be hidden behind an error message. This made it difficult for users to access the login functionality.
Solution: To resolve this, I removed the error message that was obstructing the Metamask login button. This adjustment makes the UI more responsive and ensures that the login button is easily accessible.

Files Modified:

    lib/screens/home_page.dart
    lib/screens/wallet_connect.dart
    lib/widget/header.dart
    lib/widget/homePageDecription.dart

Other modifications include updating and including some packages.

**Review by jaibhedia — APPROVED** [review]

**Pull request merged**
